- name: access ssm parameters
  hosts: localhost
  become: yes
  tasks:
      - name: access aws ssm parameters
        ansible.builtin.debug:
          msg: "{{ lookup('amazon.aws.aws_ssm', 'demo1') }}"
          region: us-east-1